baseURL = "http://teleported.in/"
theme = "hugo-theme-minos"
languageCode = "en-us"
title = "teleported.in"


[params]
    smartToc = true
    disqusShortname = "teleported.in"
    googleAnalytics = "UA-98287631-1"
