# Site settings
title: Teleported 
email: ic19929 AT gmail.com
description: "Hmm."
baseurl: "/notes"
url: "http://teleported.in"
twitter_username: the_teleported
github_username:  teleported

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['README.md']
timezone: Asia/Calcutta
include: ['.htaccess','assets']
keep_files: ['assets']
