# Site settings
title: Teleported 
email: me DOT anandsaha AT gmail.com
description: "Brain dumps of myself. Mostly computer science and maths stuff."
baseurl: ""
url: "http://teleported.in"
twitter_username: the_teleported
github_username:  teleported

# Build settings
markdown: kramdown
permalink: pretty

exclude: ['README.md']
timezone: Asia/Calcutta
include: ['.htaccess']
